# Generated by Django 2.1.7 on 2019-05-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theteam', '0005_auto_20190420_2152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='theteam_team',
        ),
    ]
