# Generated by Django 2.1.7 on 2019-05-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theteam', '0006_auto_20190517_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
