# Generated by Django 2.1.7 on 2019-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theteam', '0010_auto_20190520_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
        migrations.DeleteModel(
            name='teams_img',
        ),
    ]
