# Generated by Django 2.1.7 on 2019-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务序号')),
                ('task_class', models.CharField(max_length=20, verbose_name='任务类别')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_description', models.CharField(max_length=300, verbose_name='任务描述')),
                ('task_publisher', models.CharField(max_length=50, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'taskout_task',
            },
        ),
    ]
