# Generated by Django 2.1.7 on 2019-05-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='tasks',
        ),
    ]
