# Generated by Django 2.1.7 on 2019-05-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskout', '0003_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IMG',
            new_name='tasks_img',
        ),
    ]
