# Generated by Django 2.1.7 on 2019-05-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thingfloat', '0002_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IMG',
            new_name='things_img',
        ),
    ]
