# Generated by Django 2.1.7 on 2019-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0013_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cooent_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论数')),
                ('commentor', models.CharField(max_length=50, verbose_name='评论数')),
                ('comments', models.CharField(max_length=100, verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': '评论表',
            },
        ),
    ]
