# Generated by Django 2.1.7 on 2019-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
