# Generated by Django 2.1.7 on 2019-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0015_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论数')),
                ('comment_or', models.CharField(max_length=50, verbose_name='评论者')),
                ('comments', models.CharField(max_length=100, verbose_name='评论')),
                ('comment_time', models.DateField()),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': '评论表',
            },
        ),
    ]
