# Generated by Django 2.1.7 on 2019-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateField(verbose_name='评论时间'),
        ),
    ]
