# Generated by Django 2.1.7 on 2019-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0018_auto_20190516_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False, verbose_name='评论数'),
        ),
    ]
