# Generated by Django 2.1.7 on 2019-05-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0019_auto_20190516_1140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
