# Generated by Django 2.1.7 on 2019-05-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0020_auto_20190516_1333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='loginupin_comment',
        ),
        migrations.AlterModelTable(
            name='student',
            table='loginupin_Student',
        ),
        migrations.AlterModelTable(
            name='users',
            table='loginupin_users',
        ),
    ]
