# Generated by Django 2.1.7 on 2019-05-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0021_auto_20190517_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
