# Generated by Django 2.1.7 on 2019-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0022_delete_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
                ('img_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
