# Generated by Django 2.1.7 on 2019-05-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0023_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
